tomisModule.factory('tomisSchedulerFactory', [
	'$q',
	'$timeout',
	function($q, $timeout) {
		var factory = {};
		var deferred = $q.defer();
		var upperCase = _.memoize(function(string) {
			return string.toUpperCase();
		});

		/***REMOVE THESE ONCE THE SERIVE IS HOOKED UP ****/
		factory.getRandomNumber = function () {
			return _.random(11111, 99999).toString();
		};
		factory.getRandomMissionNumber = function generateId(len) {
			var arr = new Uint8Array((len || 40) / 2);
			window.crypto.getRandomValues(arr);
			return upperCase(_.map(arr, function(n) { return n.toString(16); }).join(""));
		}
		factory.getRandomBg = function() {
			return _.sample(['red', 'cyan', 'orange', 'pink', 'yellow', 'purple']);
		};
		/*************************************************/
		factory.getMonthString = function (monthNumber) {
			var monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
			'July', 'August', 'September', 'October', 'November', 'December'];
			return monthNames[monthNumber];
		};
		factory.lovData = {
			booGcsCd: "", //The Base of Operation Code
			timeZone: "",
			gcsInd: false,
			localInd: false,
			startDt: null,
			endDt: null
		};
		factory.gridOptions = {
			//enableSorting: true,
			columnDefs: [
				{ name:'Call Out/Initiator', field: 'call-out', enableColumnResizing: true },
				{ name:'Agency Group', field: 'agency-group', enableColumnResizing: true },
				{ name:'Agency Name', field: 'agency-name', enableColumnResizing: true},
				{ name:'Office/Agency Description', field: 'agency-description', enableColumnResizing: true}
			],
			data: [
				{
					"call-out": "Sample Callout",
					"agency-group": "Sample Agency Group",
					"agency-name": "Sample Agency Name",
					"agency-description" : "Sample Agency Description"
				}
			]
		};
		factory.cannedGcsLov = [
			{
				code: 'KYL',
				description: 'KYL'
			},
			{
				code: 'CRP',
				description: 'CRP'
			},
			{
				code: 'BMU',
				description: 'BMU'
			},
			{
				code: 'CMC',
				description: 'CMC'
			},
			{
				code: 'KYW',
				description: 'KYW'
			},
			{
				code: 'BUF',
				description: 'BUF'
			}
		];
		factory.cannedEvents = [
			{
				"missionId": 3475,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439438400000,
				"arrivalDt": 1439524800000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MKYL201500006",
				"missionDsc": "test2",
				"boo": "KYL",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-13",
				"end": "2015-08-13",
				"title": "MKYL201500006",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3449,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1438592400000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCRP201500006",
				"missionDsc": "test",
				"boo": "CRP",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-03",
				"end": "2015-08-03",
				"title": "MCRP201500006",
				"backgroundColor": "cyan",
				"stick": true
			},
			{
				"missionId": 3477,
				"assetNbr": "12345ABC",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439438400000,
				"arrivalDt": 1439524800000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MKYL201500008",
				"missionDsc": "test",
				"boo": "KYL",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-13",
				"end": "2015-08-13",
				"title": "MKYL201500008",
				"backgroundColor": "cyan",
				"stick": true
			},
			{
				"missionId": 3389,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439794800000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBMU201500004",
				"missionDsc": "hgghgh",
				"boo": "BMU",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-17",
				"end": "2015-08-17",
				"title": "MBMU201500004",
				"backgroundColor": "red",
				"stick": true
			},
			{
				"missionId": 3467,
				"assetNbr": "45",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439190000000,
				"arrivalDt": 1440572400000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCMC201500262",
				"missionDsc": "gdfgdfg",
				"boo": "CMC",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-10",
				"end": "2015-08-10",
				"title": "MCMC201500262",
				"backgroundColor": "red",
				"stick": true
			},
			{
				"missionId": 3408,
				"assetNbr": "12345ABC",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439524800000,
				"arrivalDt": 1439611200000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MKYW201500001",
				"missionDsc": "test ed",
				"boo": "KYW",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-14",
				"end": "2015-08-14",
				"title": "MKYW201500001",
				"backgroundColor": "yellow",
				"stick": true
			},
			{
				"missionId": 3469,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439352000000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBUF201500071",
				"missionDsc": "test",
				"boo": "BUF",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-12",
				"end": "2015-08-12",
				"title": "MBUF201500071",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3487,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1440486000000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MSAD201500002",
				"missionDsc": "fdfdd",
				"boo": "SAD",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-25",
				"end": "2015-08-25",
				"title": "MSAD201500002",
				"backgroundColor": "red",
				"stick": true
			},
			{
				"missionId": 3470,
				"assetNbr": "ASTAR1",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439348400000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCMC201500263",
				"missionDsc": "test",
				"boo": "CMC",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-11",
				"end": "2015-08-11",
				"title": "MCMC201500263",
				"backgroundColor": "purple",
				"stick": true
			},
			{
				"missionId": 3505,
				"assetNbr": "ROBASSET",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1441263600000,
				"arrivalDt": 1441281600000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBMU201500009",
				"missionDsc": "test",
				"boo": "BMU",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-03",
				"end": "2015-09-03",
				"title": "MBMU201500009",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3472,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439438400000,
				"arrivalDt": 1439460000000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MKYL201500004",
				"missionDsc": "test",
				"boo": "KYL",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-13",
				"end": "2015-08-13",
				"title": "MKYL201500004",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3468,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439197200000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MALP201500035",
				"missionDsc": null,
				"boo": "ALP",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-10",
				"end": "2015-08-10",
				"title": "MALP201500035",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3461,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1441090800000,
				"arrivalDt": 1441350000000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBLI201500016",
				"missionDsc": "descrition",
				"boo": "BLI",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-01",
				"end": "2015-09-01",
				"title": "MBLI201500016",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3489,
				"assetNbr": "UH11234",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1440558000000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCMC201500268",
				"missionDsc": null,
				"boo": "CMC",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-25",
				"end": "2015-08-25",
				"title": "MCMC201500268",
				"backgroundColor": "yellow",
				"stick": true
			},
			{
				"missionId": 3414,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439794800000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBMU201500007",
				"missionDsc": "test",
				"boo": "BMU",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-17",
				"end": "2015-08-17",
				"title": "MBMU201500007",
				"backgroundColor": "yellow",
				"stick": true
			},
			{
				"missionId": 3464,
				"assetNbr": "ZWW22",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1438671600000,
				"arrivalDt": 1438689600000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MYUM201500001",
				"missionDsc": "testtest",
				"boo": "YUM",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-04",
				"end": "2015-08-04",
				"title": "MYUM201500001",
				"backgroundColor": "purple",
				"stick": true
			},
			{
				"missionId": 3471,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439438400000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MMBF201500012",
				"missionDsc": "XCCXXC",
				"boo": "MBF",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-13",
				"end": "2015-08-13",
				"title": "MMBF201500012",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3300,
				"assetNbr": "DRT TEST",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1441166400000,
				"arrivalDt": 1441339200000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBUF201500043",
				"missionDsc": "test",
				"boo": "BUF",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-02",
				"end": "2015-09-02",
				"title": "MBUF201500043",
				"backgroundColor": "yellow",
				"stick": true
			},
			{
				"missionId": 2064,
				"assetNbr": "33333",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1441220400000,
				"arrivalDt": 1441911600000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MDTW201300420",
				"missionDsc": "Tst MSN desc###420",
				"boo": "DTW",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-02",
				"end": "2015-09-02",
				"title": "MDTW201300420",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3474,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439438400000,
				"arrivalDt": 1439524800000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MKYL201500005",
				"missionDsc": "test",
				"boo": "KYL",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-13",
				"end": "2015-08-13",
				"title": "MKYL201500005",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3486,
				"assetNbr": "ASTAR1",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1440471600000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCMC201500266",
				"missionDsc": "test",
				"boo": "CMC",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-24",
				"end": "2015-08-24",
				"title": "MCMC201500266",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3483,
				"assetNbr": "N12345",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439866800000,
				"arrivalDt": 1439884800000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCMC201500265",
				"missionDsc": "testtest",
				"boo": "CMC",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-17",
				"end": "2015-08-17",
				"title": "MCMC201500265",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3504,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1441263600000,
				"arrivalDt": 1441281600000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBLI201500019",
				"missionDsc": "test",
				"boo": "BLI",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-03",
				"end": "2015-09-03",
				"title": "MBLI201500019",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3479,
				"assetNbr": "8998",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439524800000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MMBF201500013",
				"missionDsc": "sdfdffd",
				"boo": "MBF",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-14",
				"end": "2015-08-14",
				"title": "MMBF201500013",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3476,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439438400000,
				"arrivalDt": 1439524800000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MKYL201500007",
				"missionDsc": "test",
				"boo": "KYL",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-13",
				"end": "2015-08-13",
				"title": "MKYL201500007",
				"backgroundColor": "cyan",
				"stick": true
			},
			{
				"missionId": 3482,
				"assetNbr": "56",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439784000000,
				"arrivalDt": 1439884800000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MJAX201500005",
				"missionDsc": "test1",
				"boo": "JAX",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-17",
				"end": "2015-08-17",
				"title": "MJAX201500005",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3488,
				"assetNbr": "TREST1223",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1440558000000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCMC201500267",
				"missionDsc": "nbhnnh",
				"boo": "CMC",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-25",
				"end": "2015-08-25",
				"title": "MCMC201500267",
				"backgroundColor": "cyan",
				"stick": true
			},
			{
				"missionId": 3466,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1439301600000,
				"arrivalDt": 1439373600000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MELP201500001",
				"missionDsc": "dkfj ioe ffdjlkff ewoirj fdjlk jlkjlklj",
				"boo": "ELP",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-11",
				"end": "2015-08-11",
				"title": "MELP201500001",
				"backgroundColor": "red",
				"stick": true
			},
			{
				"missionId": 3463,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1438574400000,
				"arrivalDt": 1438596000000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MPBG201500001",
				"missionDsc": null,
				"boo": "PBG",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-03",
				"end": "2015-08-03",
				"title": "MPBG201500001",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3495,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1442293200000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MALP201500037",
				"missionDsc": null,
				"boo": "ALP",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-15",
				"end": "2015-09-15",
				"title": "MALP201500037",
				"backgroundColor": "pink",
				"stick": true
			},
			{
				"missionId": 3499,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1442376000,
				"arrivalDt": null,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MALP201600037",
				"missionDsc": null,
				"boo": "ALP",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-16",
				"end": "2015-09-16",
				"title": "MALP201600037",
				"backgroundColor": "red",
				"stick": true
			},
			{
				"missionId": 3516,
				"assetNbr": "LRD ASSET",
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1441339200000,
				"arrivalDt": 1441357200000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MBUF201500074",
				"missionDsc": "test",
				"boo": "BUF",
				"gcs": null,
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-09-04",
				"end": "2015-09-04",
				"title": "MBUF201500074",
				"backgroundColor": "orange",
				"stick": true
			},
			{
				"missionId": 3485,
				"assetNbr": null,
				"briefStartDt": null,
				"briefEndDt": null,
				"departureDt": 1440579600000,
				"arrivalDt": 1441011600000,
				"personnelFullName": [],
				"totalPersons": 0,
				"missionNbr": "MCRP201500007",
				"missionDsc": "descritionaa",
				"boo": "CRP",
				"gcs": "CRPGCS4",
				"frequencyCd": null,
				"handoverCollection": [],
				"kuStartDt": null,
				"kuEndDt": null,
				"start": "2015-08-26",
				"end": "2015-08-26",
				"title": "MCRP201500007",
				"backgroundColor": "cyan",
				"stick": true
			}
		];

		return factory;

	}]);
